version: "3.6"
services:
  db:
    container_name: db
    image: "mongo:4.4"
    volumes:
      - ./db:/data/db
    ports:
      - 27020:27017
    environment:
      - AUTH=yes
    networks:
      - mongo_net
networks:
  mongo_net:
    driver: bridge
