#!/bin/bash

post_install() {
    xdg-desktop-menu install /usr/share/applications/sel-protocol.desktop --novendor
    xdg-settings set default-url-scheme-handler sel sel.desktop
    grep "sel=sel.desktop" /usr/share/applications/mimeapps.list
    [[ $? == 1 ]] && echo -e "\nx-scheme-handler/sel=sel.desktop\n" | tee -a /usr/share/applications/mimeapps.list
}

pre_upgrade() {
    xdg-desktop-menu install /usr/share/applications/sel-protocol.desktop --novendor
    xdg-settings set default-url-scheme-handler sel sel-protocol.desktop
    grep "sel=sel.desktop" /usr/share/applications/mimeapps.list
    [[ $? == 1 ]] && echo -e "\nx-scheme-handler/sel=sel.desktop\n" | tee -a /usr/share/applications/mimeapps.list
}

post_remove() {
    xdg-desktop-menu uninstall /usr/share/applications/sel-protocol.desktop
    sed -i "/sel=sel.desktop/d" /usr/share/applications/mimeapps.list
}